export const weatherImages = {
    'Partly cloudy' : require('../assets/icons/partlycloudy.png'),
    'Moderate rain' : require('../assets/icons/partlyrainpossible.png'),
    'Patchy rain nearby' : require('../assets/icons/partlyrainpossible.png'),
    'Sunny' : require('../assets/icons/sunny.png'),
    'Clear' : require('../assets/icons/sunny.png'),
    'Overcast' : require('../assets/icons/overcast.png'),
    'Cloudy' : require('../assets/icons/overcast.png'),
    'Light drizzle' : require('../assets/icons/moderaterain.png'),
    'Light rain shower' : require('../assets/icons/moderaterain.png'),
    'Moderate rain at times' : require('../assets/icons/moderaterainattimes.png'),
    'Heavy rain' : require('../assets/icons/heavyrain.png'),
    'Heavy rain at time' : require('../assets/icons/heavyrain.png'),
    'Moderate or heavy freezing rain' : require('../assets/icons/heavyrain.png'),
    'Moderate or heavy rain shower' : require('../assets/icons/heavyrain.png'),
    'Moderate or heavy rain with thunder' : require('../assets/icons/heavyrain.png'),
    'Other' : require('../assets/icons/moderaterain.png'),
    'Thundery outbreaks in nearby' : require('../assets/icons/Thunderyoutbreaksinnearby.png'),
}